services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

